[package]
name = "cascade"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.16"
petgraph = "0.6.0"

nanoid = "0.4.0"

tokio = { version = "^1.32.0", features = ["full"] }

async-trait = "0.1.53"