[package]
name = "cascade_connection"
version = "0.1.0"
edition = "2021"

[dependencies]
async-channel = "1.9.0"

serde = { version = "1.0.188", features = ["derive"] }

cascade_payload = { path = "../cascade_payload" }
