[package]
name = "cascade_component_std"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.20"
async-trait = "0.1.73"

serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"

cascade_api = { path = "../cascade_api" }